"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { BookmarkX, Check, Folder, Loader2, NotebookPen, Search, Tag, Trash2, X } from "lucide-react";
import { AdCard } from "@/components/ad-card";
import { AdDetailDrawer } from "@/components/ad-detail";
import { EmptyState, Button, Skeleton } from "@/components/ui";
import type { Collection, NormalizedAd } from "@/lib/types";

type Saved = { id: string; notes: string | null; createdAt: string; ad: NormalizedAd; tags: { id: string; name: string }[]; collectionIds: string[] };

export function SavedAdsView({ collectionId }: { collectionId?: string }) {
  const [items, setItems] = useState<Saved[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [details, setDetails] = useState<NormalizedAd | null>(null); const [editing, setEditing] = useState<Saved | null>(null); const [toast, setToast] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/saved-ads${collectionId ? `?collectionId=${collectionId}` : ""}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(data.savedAds); } catch (error) { setError(error instanceof Error ? error.message : "Unable to load saved ads."); } finally { setLoading(false); } }, [collectionId]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 2400); return () => window.clearTimeout(timer); }, [toast]);
  const filtered = useMemo(() => { const q = query.toLowerCase(); return items.filter(item => !q || [item.ad.advertiserName,item.ad.headline,item.ad.body,item.notes,...item.tags.map(t=>t.name)].some(value => value?.toLowerCase().includes(q))); }, [items, query]);
  async function remove(id: string) { if (!confirm("Remove this ad from your saved library?")) return; const response = await fetch(`/api/saved-ads?id=${id}`, { method: "DELETE" }); if (response.ok) setItems(current => current.filter(item => item.id !== id)); }
  async function share(ad: NormalizedAd) { await copyText(`${window.location.origin}/discover?ad=${encodeURIComponent(ad.externalAdId)}`); setToast("Link copied"); }
  if (loading) return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-96" />)}</div>;
  if (error) return <EmptyState icon={<BookmarkX />} title="Saved ads unavailable" body={error} action={<Button variant="secondary" onClick={load}>Retry</Button>} />;
  return <><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" size={16} /><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search saved creatives, notes, tags…" className="h-11 w-full rounded-lg border border-line pl-10 pr-3 text-sm outline-none focus:border-signal" /></div><p className="text-xs font-medium text-muted">{filtered.length} saved creative{filtered.length === 1 ? "" : "s"}</p></div>{!filtered.length ? <EmptyState icon={<BookmarkX />} title={items.length ? "No saved ads match" : "Your swipe file is empty"} body={items.length ? "Try another search term." : "Save winning ads while browsing and organize them here."} /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{filtered.map(item => <div key={item.id}><AdCard ad={item.ad} saved swipeFileCount={item.collectionIds.length} onOpen={()=>setDetails(item.ad)} onSave={()=>undefined} onSwipeFile={()=>setEditing(item)} onShare={()=>share(item.ad)} /><div className="-mt-3 mx-2 flex items-center gap-1 rounded-b-xl border border-t-0 border-line bg-surface px-2 pb-2 pt-5"><button onClick={()=>setEditing(item)} className="flex min-h-9 flex-1 items-center gap-1.5 rounded-md px-2 text-xs font-semibold text-muted hover:bg-white hover:text-ink"><NotebookPen size={14} />Notes & tags</button><button onClick={()=>remove(item.id)} aria-label="Remove saved ad" className="grid size-9 place-items-center rounded-md text-muted hover:bg-white hover:text-signal"><Trash2 size={14} /></button></div></div>)}</div>}{details && <AdDetailDrawer ad={details} onClose={()=>setDetails(null)} onSave={()=>{ const item=items.find(i=>i.ad.id===details.id); if(item)setEditing(item); }} />}{editing && <NotesModal item={editing} onClose={()=>setEditing(null)} onChange={updated=>setItems(current=>current.map(item=>item.id===updated.id?updated:item))} />}{toast&&<div className="fixed bottom-4 left-1/2 z-[90] -translate-x-1/2 rounded-lg border border-line bg-white px-4 py-3 text-sm font-semibold shadow-card" role="status">{toast}</div>}</>;
}

async function copyText(value: string) {
  if (navigator.clipboard?.writeText) return navigator.clipboard.writeText(value);
  const field = document.createElement("textarea");
  field.value = value;
  field.style.position = "fixed";
  field.style.opacity = "0";
  document.body.appendChild(field);
  field.select();
  document.execCommand("copy");
  document.body.removeChild(field);
}

function NotesModal({ item, onClose, onChange }: { item: Saved; onClose: ()=>void; onChange:(item:Saved)=>void }) {
  const [notes,setNotes]=useState(item.notes||""); const [tag,setTag]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [collections,setCollections]=useState<Collection[]>([]); const [collectionIds,setCollectionIds]=useState(item.collectionIds);
  useEffect(()=>{fetch("/api/collections").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setCollections(data.collections);}).catch(error=>setError(error instanceof Error?error.message:"Unable to load swipe files."));},[]);
  async function saveNotes(){setBusy(true);const response=await fetch("/api/saved-ads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,notes})});setBusy(false);if(!response.ok){const data=await response.json();return setError(data.error);}onChange({...item,notes});}
  async function saveCollections(){setBusy(true);setError("");const response=await fetch("/api/saved-ads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,collectionIds})});const data=await response.json();setBusy(false);if(!response.ok)return setError(data.error);onChange({...item,collectionIds});}
  async function addTag(event:FormEvent){event.preventDefault();if(!tag.trim())return;setBusy(true);const response=await fetch("/api/tags",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({savedAdId:item.id,name:tag})});const data=await response.json();setBusy(false);if(!response.ok)return setError(data.error);onChange({...item,tags:[...item.tags.filter(t=>t.id!==data.tag.id),data.tag]});setTag("");}
  async function removeTag(tagId:string){const response=await fetch(`/api/tags?savedAdId=${item.id}&tagId=${tagId}`,{method:"DELETE"});if(response.ok)onChange({...item,tags:item.tags.filter(t=>t.id!==tagId)});}
  return <div className="fixed inset-0 z-[80] grid place-items-end bg-black/25 sm:place-items-center sm:p-4" onMouseDown={onClose}><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 shadow-2xl sm:max-w-lg sm:rounded-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Creative notes</h2><p className="mt-1 text-xs text-muted">{item.ad.advertiserName}</p></div><button onClick={onClose} className="grid size-10 place-items-center"><X size={18}/></button></div><label className="mt-5 block text-xs font-semibold text-muted">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5} maxLength={5000} placeholder="Capture the hook, angle, offer, or why this creative matters…" className="mt-2 w-full resize-none rounded-lg border border-line p-3 text-sm leading-6 outline-none focus:border-signal" /></label><Button onClick={saveNotes} className="mt-2" disabled={busy}>{busy?<Loader2 className="animate-spin" size={15}/>:<Check size={15}/>}Save notes</Button><div className="mt-6 border-t border-line pt-5"><p className="flex items-center gap-1.5 text-xs font-semibold text-muted"><Folder size={13}/>Swipe files</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{collections.map(collection=><label key={collection.id} className="flex min-h-10 cursor-pointer items-center gap-2 rounded-lg border border-line px-3 text-xs font-medium"><input type="checkbox" className="accent-signal" checked={collectionIds.includes(collection.id)} onChange={()=>setCollectionIds(current=>current.includes(collection.id)?current.filter(id=>id!==collection.id):[...current,collection.id])}/><span className="truncate">{collection.name}</span></label>)}</div>{collections.length?<Button variant="secondary" className="mt-3" onClick={saveCollections} disabled={busy}>{busy?<Loader2 className="animate-spin" size={15}/>:<Check size={15}/>}Save folders</Button>:<p className="mt-2 text-xs text-muted">Create a swipe file first, then assign this creative to it.</p>}</div><div className="mt-6 border-t border-line pt-5"><p className="text-xs font-semibold text-muted">Tags</p><div className="mt-2 flex flex-wrap gap-2">{item.tags.map(current=><span key={current.id} className="flex items-center gap-1 rounded-full bg-red-50 px-2.5 py-1.5 text-xs font-medium text-signal"><Tag size={11}/>{current.name}<button onClick={()=>removeTag(current.id)}><X size={11}/></button></span>)}</div><form onSubmit={addTag} className="mt-3 flex gap-2"><input value={tag} onChange={e=>setTag(e.target.value)} placeholder="UGC, Hook, Social Proof…" className="h-10 min-w-0 flex-1 rounded-lg border border-line px-3 text-sm outline-none focus:border-signal"/><Button type="submit" variant="secondary" disabled={busy||!tag.trim()}>Add tag</Button></form></div>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-signal">{error}</p>}</div></div>;
}
