"use client";

import { useEffect, useState } from "react";
import { Check, FolderPlus, Loader2, Plus, X } from "lucide-react";
import { Button } from "@/components/ui";
import type { SwipeFile, NormalizedAd } from "@/lib/types";

export function SaveModal({ ad, onClose }: { ad: NormalizedAd; onClose: () => void }) {
  const [collections, setCollections] = useState<SwipeFile[]>([]); const [selected, setSelected] = useState<string[]>([]); const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [done, setDone] = useState(false);
  useEffect(() => { fetch("/api/swipe-files").then(async r => { if (!r.ok) throw new Error((await r.json()).error); return r.json(); }).then(data => setCollections(Array.isArray(data) ? data.filter((collection: SwipeFile) => !collection.isSystem) : [])).catch(error => setError(error.message)); }, []);
  async function createAndSelect() { if (!name.trim()) return; setBusy(true); setError(""); const response = await fetch("/api/swipe-files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error); const collection = { ...data.collection, createdAt: data.collection.created_at, updatedAt: data.collection.updated_at }; setCollections(current => [collection, ...current]); setSelected(current => [...current, collection.id]); setName(""); setCreating(false); }
  async function save() { setBusy(true); setError(""); try { const defaultResponse = await fetch("/api/swipe-files/items", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ adId: ad.id, externalAdId: ad.externalId || ad.id }) }); const defaultData = await defaultResponse.json(); if (!defaultResponse.ok) throw new Error(defaultData.error || "Unable to save this ad."); await Promise.all(selected.map(async swipeFileId => { const response = await fetch("/api/swipe-files/items", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ adId: ad.id, externalAdId: ad.externalId || ad.id, swipeFileId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to save this ad."); })); setDone(true); setTimeout(onClose, 900); } catch (error) { setError(error instanceof Error ? error.message : "Unable to save this ad."); } finally { setBusy(false); } }
  return <div className="fixed inset-0 z-[70] grid place-items-end bg-black/25 p-0 sm:place-items-center sm:p-4" role="dialog" aria-modal="true" aria-label="Save to swipe file" onMouseDown={onClose}><div className="w-full rounded-t-2xl bg-white p-5 shadow-2xl sm:max-w-md sm:rounded-2xl" onMouseDown={event => event.stopPropagation()}><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold tracking-tight">Save to swipe file</h2><p className="mt-1 text-xs text-muted">Choose one or more folders for this creative.</p></div><button onClick={onClose} className="grid size-10 place-items-center rounded-lg hover:bg-surface" aria-label="Close"><X size={18} /></button></div>{done ? <div className="my-10 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-surface-blue text-brand"><Check /></span><p className="mt-3 font-semibold">Saved to your swipe file</p></div> : <><div className="mt-5 max-h-60 space-y-2 overflow-auto">{collections.map(collection => { const checked = selected.includes(collection.id); return <label key={collection.id} className="flex min-h-12 cursor-pointer items-center gap-3 rounded-lg border border-line px-3 hover:bg-surface"><input type="checkbox" className="accent-brand" checked={checked} onChange={() => setSelected(current => checked ? current.filter(id => id !== collection.id) : [...current, collection.id])} /><span className="flex-1 text-sm font-medium">{collection.name}</span><span className="text-xs text-muted">{collection.adCount ?? 0}</span></label>; })}{!collections.length && !error && <p className="rounded-lg bg-surface p-4 text-sm text-muted">No folders yet. Create your first one below.</p>}</div>{creating ? <div className="mt-3 flex gap-2"><input autoFocus value={name} onChange={event => setName(event.target.value)} onKeyDown={event => event.key === "Enter" && createAndSelect()} placeholder="High Performing Ads" className="h-11 min-w-0 flex-1 rounded-lg border border-line px-3 text-sm focus:border-brand focus:outline-none" /><Button variant="secondary" onClick={createAndSelect} disabled={busy || !name.trim()}>Create</Button></div> : <button onClick={() => setCreating(true)} className="mt-3 flex min-h-11 w-full items-center gap-2 rounded-lg px-2 text-sm font-semibold text-brand hover:bg-brand/10"><FolderPlus size={17} />Create folder</button>}{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-xs leading-5 text-signal">{error}</p>}<div className="mt-5 flex justify-end gap-2 border-t border-line pt-4"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button variant="primary" onClick={save} disabled={busy}>{busy ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}Save ad</Button></div></>}</div></div>;
}
