export const NICHES = [
  { id: "apparel-fashion", label: "Apparel & Fashion" },
  { id: "beauty-skincare", label: "Beauty & Skincare" },
  { id: "health-wellness", label: "Health & Wellness" },
  { id: "fitness", label: "Fitness" },
  { id: "supplements", label: "Supplements" },
  { id: "food-beverage", label: "Food & Beverage" },
  { id: "restaurants-delivery", label: "Restaurants & Delivery" },
  { id: "consumer-electronics", label: "Consumer Electronics" },
  { id: "mobile-accessories", label: "Mobile & Accessories" },
  { id: "gaming", label: "Gaming" },
  { id: "home-furniture", label: "Home & Furniture" },
  { id: "home-improvement", label: "Home Improvement" },
  { id: "kitchen-appliances", label: "Kitchen & Appliances" },
  { id: "real-estate", label: "Real Estate" },
  { id: "automotive", label: "Automotive" },
  { id: "travel-hospitality", label: "Travel & Hospitality" },
  { id: "education", label: "Education" },
  { id: "online-courses", label: "Online Courses" },
  { id: "finance", label: "Finance" },
  { id: "fintech", label: "Fintech" },
  { id: "insurance", label: "Insurance" },
  { id: "saas", label: "SaaS" },
  { id: "b2b-services", label: "B2B Services" },
  { id: "business-marketing", label: "Business & Marketing" },
  { id: "e-commerce", label: "E-commerce" },
  { id: "media-entertainment", label: "Media & Entertainment" },
  { id: "music", label: "Music" },
  { id: "sports", label: "Sports" },
  { id: "pets", label: "Pets" },
  { id: "baby-parenting", label: "Baby & Parenting" },
  { id: "toys-kids", label: "Toys & Kids" },
  { id: "jewellery-accessories", label: "Jewellery & Accessories" },
  { id: "luxury", label: "Luxury" },
  { id: "gifts", label: "Gifts" },
  { id: "art-collectibles", label: "Art & Collectibles" },
  { id: "books-publishing", label: "Books & Publishing" },
  { id: "events", label: "Events" },
  { id: "ngos-causes", label: "NGOs & Social Causes" },
  { id: "professional-services", label: "Professional Services" },
  { id: "legal-services", label: "Legal Services" },
  { id: "recruitment-careers", label: "Recruitment & Careers" },
  { id: "telecom", label: "Telecom" },
  { id: "dating-relationships", label: "Dating & Relationships" },
  { id: "apps-software", label: "Apps & Software" },
  { id: "local-services", label: "Local Services" },
  { id: "other", label: "Other" },
];

export const CONTENT_STYLES = [
  { id: "ugc", label: "UGC" },
  { id: "creator-led", label: "Creator-led" },
  { id: "founder-led", label: "Founder-led" },
  { id: "talking-head", label: "Talking head" },
  { id: "testimonial", label: "Testimonial" },
  { id: "product-demonstration", label: "Product demonstration" },
  { id: "unboxing", label: "Unboxing" },
  { id: "problem-solution", label: "Problem–solution" },
  { id: "before-and-after", label: "Before and after" },
  { id: "how-to-tutorial", label: "How-to / Tutorial" },
  { id: "educational", label: "Educational" },
  { id: "listicle", label: "Listicle" },
  { id: "storytelling", label: "Storytelling" },
  { id: "lifestyle", label: "Lifestyle" },
  { id: "product-showcase", label: "Product showcase" },
  { id: "animation", label: "Animation" },
  { id: "motion-graphics", label: "Motion graphics" },
  { id: "screen-recording", label: "Screen recording" },
  { id: "podcast-clip", label: "Podcast clip" },
  { id: "interview", label: "Interview" },
  { id: "meme", label: "Meme" },
  { id: "static-graphic", label: "Static graphic" },
  { id: "offer-led", label: "Offer-led" },
  { id: "comparison", label: "Comparison" },
  { id: "social-proof", label: "Social proof" },
  { id: "voice-over", label: "Voice-over" },
  { id: "text-led", label: "Text-led" },
  { id: "cinematic", label: "Cinematic" },
  { id: "other", label: "Other" },
];

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "hi", label: "Hindi" },
  { code: "bn", label: "Bengali" },
  { code: "mr", label: "Marathi" },
  { code: "te", label: "Telugu" },
  { code: "ta", label: "Tamil" },
  { code: "gu", label: "Gujarati" },
  { code: "ur", label: "Urdu" },
  { code: "kn", label: "Kannada" },
  { code: "ml", label: "Malayalam" },
  { code: "pa", label: "Punjabi" },
  { code: "or", label: "Odia" },
  { code: "as", label: "Assamese" },
  { code: "es", label: "Spanish" },
  { code: "fr", label: "French" },
  { code: "de", label: "German" },
  { code: "pt", label: "Portuguese" },
  { code: "it", label: "Italian" },
  { code: "nl", label: "Dutch" },
  { code: "ar", label: "Arabic" },
  { code: "tr", label: "Turkish" },
  { code: "ru", label: "Russian" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "zh", label: "Mandarin Chinese" },
  { code: "id", label: "Indonesian" },
  { code: "vi", label: "Vietnamese" },
  { code: "th", label: "Thai" },
];

export const MARKETS = [
  { code: "US", label: "United States" },
  { code: "IN", label: "India" },
  { code: "GB", label: "United Kingdom" },
  { code: "CA", label: "Canada" },
  { code: "AU", label: "Australia" },
  { code: "DE", label: "Germany" },
  { code: "FR", label: "France" },
  { code: "BR", label: "Brazil" },
  { code: "MX", label: "Mexico" },
  { code: "JP", label: "Japan" },
  { code: "SG", label: "Singapore" },
  { code: "AE", label: "United Arab Emirates" },
];

export type NicheId = typeof NICHES[number]["id"];
export type ContentStyleId = typeof CONTENT_STYLES[number]["id"];
